Hooks
brusni4ka/ITA02.11 pull request #12
Opened 2021-01-24 18:55 UTC by LanskayaIrina

2021-01-26 22:08 UTC, brusni4ka requested changes

2021-01-26 22:08 UTC, brusni4ka commented on Ira/my-app-video/src/App.tsx
> +                   />}
render => component={FilmPage} 
I already asked you to fix it

2021-01-26 22:08 UTC, brusni4ka commented on Ira/my-app-video/src/components/filmCard/index.ts
> +export default connector(FilmCard);
better to use useSelector

2021-01-26 22:08 UTC, brusni4ka commented on Ira/my-app-video/src/components/filmPage/FilmPage.tsx
> +  }, [location]);
initPage will be called two times in a row. you can remove second use Effect and add location dependancy in the first one

2021-01-26 22:08 UTC, brusni4ka commented on Ira/my-app-video/src/components/home/Home.tsx
> +  }, [location]);
leave one useEffect. same problem as in Films page

2021-01-26 22:08 UTC, brusni4ka commented on Ira/my-app-video/src/components/filmPage/FilmPage.tsx
> +    dispatch(fetchMovies(payLoadParams));
useEffect that subscribed on location will be called when you do history.push. You have an issue in logic

2021-01-26 22:08 UTC, brusni4ka commented on Ira/my-app-video/src/components/filmPage/FilmPage.tsx
> +        />
better to move "Loading..." inside of FilmList component

2021-01-26 22:08 UTC, brusni4ka commented on Ira/my-app-video/src/components/home/Home.tsx
> +    history.push(`/search?${newParams}`);
get movies will be called on history.push. Logic issue

2021-01-26 22:08 UTC, brusni4ka commented on Ira/my-app-video/src/components/home/Home.tsx
> +    dispatch(fetchMovies({...params, sortBy: params.sortBy || 'release_date', page: btnId}))
Why you still using strings like 'release_date'  if you have an ENUM ???

2021-01-27 10:10 UTC, LanskayaIrina commented on Ira/my-app-video/src/App.tsx
> +                   />}
I need to pass props

2021-01-28 17:10 UTC, brusni4ka approved these changes

2021-01-28 17:10 UTC, merged